sudo: false
language: bash
notifications:
    email:
        on_success: never
os:
    - linux
    - osx
before_install:
    - .ci/before-install.sh
    - export PATH=$PATH:~/env/bin
script: bats -t test
